// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SimplBlog.Models;
using System;

namespace SimplBlog.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20180328074320_crop-Category-tb-and-edit-BlogTb-to-CategoryBlTb")]
    partial class cropCategorytbandeditBlogTbtoCategoryBlTb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimplBlog.Models.CategoryBl", b =>
                {
                    b.Property<int>("CateBlId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Url");

                    b.HasKey("CateBlId");

                    b.ToTable("CategoryBls");
                });

            modelBuilder.Entity("SimplBlog.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CateBlId");

                    b.Property<string>("Content");

                    b.Property<string>("Title");

                    b.HasKey("PostId");

                    b.HasIndex("CateBlId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SimplBlog.Models.Post", b =>
                {
                    b.HasOne("SimplBlog.Models.CategoryBl")
                        .WithMany("Posts")
                        .HasForeignKey("CateBlId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
